PREFIX schema1: <http://schema.org/>
PREFIX : <http://ontology.daniel-motz.de/ontology#>

SELECT (AVG(?price) AS ?avgPrice) WHERE {
    ?pizza rdf:type :Pizza ;
           :enthaeltZutat :tomato, :Mozzarella ;
           schema1:price ?price ;
           schema1:priceCurrency ?currency .

    # Exclude pizzas with any other ingredient
    FILTER NOT EXISTS {
        ?pizza :enthaeltZutat ?otherZutat .
        FILTER (?otherZutat != :tomato && ?otherZutat != :Mozzarella)
    }

    FILTER (str(?price) != "NaN")
}